apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-demo-app
spec:
  selector:
    matchLabels:
      app: spinnaker-demo-app
  replicas: 2
  template:
    metadata:
      labels:
        app: spinnaker-demo-app
    spec:
      containers:
      - name: app
        image: mansoor1/spinnaker-demo-app
        ports:
        - containerPort: 8080

